version: '2'
services:
  baseenv:
    environment:
      - DJANGO_DEBUG=false
      # hardened security compared to default settings.
      - DJANGO_SECURE_BROWSER_XSS_FILTER=true
      - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true
      - DJANGO_LOG_LEVEL=ERROR
      # Logging
      - PYTHONUNBUFFERED=non-empty-string
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      # We enable Python hash randomization to protect Django from certain DoS attacks.
      # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#python-options
      - PYTHONHASHSEED=random
  frontendbase:
    extends:
      service: baseenv
    expose:
      - "8000"
    environment:
      # port and host application listens
      - APP_PORT=8000
      - APP_HOST=0.0.0.0
      # hardened security compared to default settings.
      - DJANGO_SETTINGS_MODULE=web_frontend.config.settings.production
      - DJANGO_STATIC_ROOT=/data/static
      - DJANGO_MEDIA_ROOT=/data/media
      - DJANGO_RESULT_MEDIA_ROOT=/results
      - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
  conversionbase:
    extends:
      service: baseenv
    environment:
      # port and host application listens
      - APP_PORT=8901
      - APP_HOST=0.0.0.0
      # shared data
      - DJANGO_STATIC_ROOT=/data/static
      - DJANGO_MEDIA_ROOT=/data/media
      - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
      # shared pbf planet file
      - OSMAXX_CONVERSION_SERVICE_PBF_PLANET_FILE_PATH=/var/data/osm-planet/pbf/planet-latest.osm.pbf
