version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./docker_entrypoint/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend-media:/data/frontend/media
    depends_on:
      - frontend
    networks:
      - osmaxx-internal
  osm_importer:
    environment:
      - ram_cache=2000  # in megabytes
      - num_processes=8
      - osmupdate_extra_params=--base-url=download.geofabrik.de/europe/monaco-updates/
      - osm_planet_mirror=http://download.geofabrik.de/
      - osm_planet_path_relative_to_mirror=europe/monaco-latest.osm.pbf
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./osmaxx:/home/py/osmaxx
      - ./web_frontend:/home/py/web_frontend
      - ./osmaxx_conversion_service:/home/py/osmaxx_conversion_service
    command: [honcho, -f, ./web_frontend/Procfile.django.prod, start]
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=insecure!1
      - DJANGO_SETTINGS_MODULE=web_frontend.config.settings.local
      - DJANGO_DEBUG=true
  mediator:
    build:
      context: .
      dockerfile: Dockerfile.mediator
    volumes:
      - ./osmaxx:/home/py/osmaxx
      - ./web_frontend:/home/py/web_frontend
      - ./osmaxx_conversion_service:/home/py/osmaxx_conversion_service
    command: [honcho, -f, ./osmaxx_conversion_service/Procfile.mediator.prod, start]
    environment:
      - DJANGO_SECRET_KEY=insecure!2
      - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.local
  worker:
    extends:
      file: docker-compose-common.yml
      service: conversionbase
    volumes:
      - ./osmaxx:/home/py/osmaxx
      - ./web_frontend:/home/py/web_frontend
      - ./osmaxx_conversion_service:/home/py/osmaxx_conversion_service
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: [honcho, -f, ./osmaxx_conversion_service/Procfile.worker, start]
    environment:
      - DJANGO_SECRET_KEY=insecure!3
      - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.local
  world-database:
    command: postgres -B 1GB -F -N 512 -S 1GB --max_wal_size=1GB
    ports:
      - "5433:5432"
  osm_importer:
    environment:
      - ram_cache=2000  # in megabytes
      - num_processes=8
      - osmupdate_extra_params=--base-url=download.geofabrik.de/europe/monaco-updates/
      - osm_planet_mirror=http://download.geofabrik.de/
      - osm_planet_path_relative_to_mirror=europe/monaco-latest.osm.pbf
  osmboundaries-database:
    command: postgres -B 1GB -F -S 1GB
    ports:
      - "5442:5432"
